version: '3'
services:
  jarr-server:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/server
    ports:
      - "127.0.0.1:8500:8000"
    volumes:
      - /etc/jarr:/etc/jarr:ro
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      jarr:
  jarr-front:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/front
    depends_on:
      - jarr-server
    networks:
      - jarr
  jarr-worker:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/server
    volumes:
      - /etc/jarr:/etc/jarr:ro
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - jarr
  rabbitmq:
    image: rabbitmq
    networks:
      - jarr
  redis:
    image: redis
    networks:
      - jarr
  postgres:
    image: postgres:11
    networks:
      - jarr

networks:
  jarr:
